---
- name: update apt if needed
  apt:  update_cache=yes cache_valid_time=3600
  sudo: yes

- name: set hostname
  hostname: name="{{ node_hostname }}"
  sudo: yes

- name: install git
  apt: name=git
  sudo: yes

- name: Update hosts file
  lineinfile: >
    dest=/etc/hosts
    regexp='{{ item.hostname }}$'
    line='{{ item.ip }} {{ item.hostname }}'
    state=present
  with_items: openstack_nodes
  sudo: yes
