---
- name: update apt if needed
  apt:  update_cache=yes cache_valid_time=3600
  sudo: yes

- name: set hostname
  hostname: name="{{ node_hostname }}"
  sudo: yes

- name: install base packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - ntp
    - ntpdate
  sudo: yes

- name: Set preferred ntp server
  lineinfile:
    dest: /etc/ntp.conf
    insertafter: "^# Specify one or more NTP servers."
    regexp: "^server {{ preferred_ntp_server }}"
    line: "server {{ preferred_ntp_server }}"
    state: present
  notify:
    - stop ntp service
    - update date with ntp
    - start ntp service
  sudo: yes
  when: preferred_ntp_server is defined

- name: Update hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ item.hostname }}$'
    line: '{{ item.ip }} {{ item.hostname }}'
    state: present
  with_items: openstack_nodes
  sudo: yes

- name: Set Time Zone
  template:
    src: timezone
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  notify:
    - update timezone
  sudo: yes
  when: preferred_timezone is defined
