---
- hosts: all-nodes
  roles:
    - common

- hosts: keystone-idp
  roles:
    - keystone-federation
    - keystone-idp
  vars_files:
    - vars/keystone_idp_vars.yaml

- hosts: keystone-sp
  roles:
    - keystone-federation
    - keystone-sp
  tasks:
    - include: roles/keystone-sp/tasks/connect-to-idp.yaml

# Call IdPs again, register the SPs using REST API
- hosts: keystone-idp
  tasks:
    - include: roles/keystone-idp/tasks/register-sp.yaml

- hosts: keystone-sp
  tasks:
    - include: roles/keystone-sp/tasks/register-idp.yaml