---
- hosts: keystone-idp
  roles:
    - keystone-federation
    - keystone-idp
  vars_files:
    - vars/keystone_idp_vars.yaml

- hosts: keystone-sp
  roles:
    - keystone-federation
    - keystone-sp
