---
- name: check for registered SP
  uri:
     url: "http://{{ node_hostname }}:35357/v3/OS-FEDERATION/service_providers/{{ item.cloud }}"
     method: GET
     HEADER_X-Auth-Token: "password"
     status_code: [200, 404]
  register: "{{ item.name }}_registered_on_{{ node_hostname }}"
  with_items: "{{ openstack_nodes|byattr('role', 'keystone-sp') }}"

- name: register SP
  uri:
     url: "http://{{ node_hostname }}:35357/v3/OS-FEDERATION/service_providers/{{ item.cloud }}"
     method: PUT
     body: "{ \"service_provider\": {\"auth_url\": \"http://{{ item.hostname }}:35357/v3/OS-FEDERATION/identity_providers/{{ item.cloud }}/protocols/saml2/auth\", \"sp_url\": \"https://{{ item.hostname }}:5000/Shibboleth.sso/SAML2/ECP\", \"enabled\": true} }"
     body_format: json
     HEADER_X-Auth-Token: "password"
     HEADER_Content-Type: "application/json"
     status_code: 201
  when: "{{ item.name }}_registered_on_{{ node_hostname }}.error is defined"
  with_items: "{{ openstack_nodes|byattr('role', 'keystone-sp') }}"
