---
- name: check for registered SP
  uri:
     url: "https://{{ node_hostname }}:35357/v3/OS-FEDERATION/service_providers/{{ item.cloud }}"
     method: GET
     HEADER_X-Auth-Token: "password"
     status_code: [200, 404]
  with_items: "{{ openstack_nodes|byattr('role', 'keystone-sp') }}"
  register: registered_sps

# The loop variable contains the results from the check above and have the form:
# Error, missing SP
# { 'status': 404,
#   'content_length': 102,
#   'changed': False,
#   'vary': 'X-Auth-Token',
#   'x_openstack_request_id': 'req-d132e663-4321-406d-8b1b-2c048e6139b8',
#   'item': <node data from nodes.yaml>, this is the capture item from above,
#   'json': {'error': {'message': <msg>, 'code': 404, 'title': 'Not Found'}},
#   'content_type': 'application/json',
#   'invocation': {'module_name': u'uri', 'module_args': ''},
#   'date': 'Wed, 19 Aug 2015 00:04:48 GMT',
#   'redirected': False,
#   'server': 'Apache/2.4.7 (Ubuntu)'
# }
# Success
# { 'status': 200,
#   'content_length': 102,
#   'changed': False,
#   'vary': 'X-Auth-Token',
#   'x_openstack_request_id': 'req-d132e663-4321-406d-8b1b-2c048e6139b8',
#   'item': <node data from nodes.yaml>, this is the capture item from above,
#   'json': {},
#   'content_type': 'application/json',
#   'invocation': {'module_name': u'uri', 'module_args': ''},
#   'date': 'Wed, 19 Aug 2015 00:04:48 GMT',
#   'redirected': False,
#   'server': 'Apache/2.4.7 (Ubuntu)'
# }
- name: register SP
  uri:
     url: "https://{{ node_hostname }}:35357/v3/OS-FEDERATION/service_providers/{{ item.item.cloud }}"
     method: PUT
     body: "{{ lookup('template', 'register-sp.json.j2') }}"
     body_format: json
     HEADER_X-Auth-Token: "password"
     HEADER_Content-Type: "application/json"
     status_code: 201
     validate_certs: no
  when: "{{ item.status == 404 }}"
  with_items: "{{ registered_sps.results }}"
