---
- name: copy metadata
  command: "scp -i /home/vagrant/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no vagrant@{{ item.hostname }}:/etc/keystone/saml2_idp_metadata.xml /etc/shibboleth/idp-{{ item.hostname }}.xml"
  args:
    creates: "/etc/shibboleth/idp-{{ item.hostname }}.xml"
  with_items: "{{ openstack_nodes|byattr('role', 'keystone-idp') }}"
  sudo: yes
  notify: Restart shibd
