---
- name: update apt if needed
  apt:  update_cache=yes cache_valid_time=3600
  sudo: yes

- name: install shibboleth requirements
  apt: pkg={{ item }} state=latest
  with_items:
    - libapache2-mod-shib2
  sudo: yes

- name: Copy apache2 federation config file
  copy:
  args:
   src: keystone-federation.conf
   dest: /etc/apache2/sites-available
   owner: root
   group: root
   mode: 0644
  sudo: yes

- name: Enable federation site
  command: a2ensite keystone-federation creates=/etc/apache2/sites-enabled/keystone-federation.conf
  sudo: yes

- name: Enable required apache2 modules
  apache2_module: name={{ item }} state=present
  with_items:
    - ssl
    - shib2
  sudo: yes

- name: generate Shibboleth keys
  command: shib-keygen -y 5 creates=/etc/shibboleth/sp-key.pem
  sudo: yes

- name: Copy Shibboleth2.xml
  template:
  args:
    src: shibboleth2.xml.j2
    dest: /etc/shibboleth/shibboleth2.xml
    owner: root
    group: root
    mode: 0644
  sudo: yes

- name: Copy attributes map xml
  copy:
  args:
    src: attribute-map.xml
    dest: /etc/shibboleth/attribute-map.xml
    owner: root
    group: root
    mode: 0644
  sudo: yes

- name: enable SAML SSO debugging for shibd
  lineinfile:
  args:
    line: "log4j.category.Shibboleth.SSO.SAML2=DEBUG, shibd_log"
    insertafter: EOF
    state: present
    dest: /etc/shibboleth/shibd.logger
  sudo: yes

- name: uncomment OpenSAML decoder debugging
  lineinfile: line="log4j.category.OpenSAML.MessageDecoder=DEBUG" regexp="^\s*#?\s*log4j.category.OpenSAML.MessageDecoder=DEBUG" state=present dest=/etc/shibboleth/shibd.logger
  sudo: yes

- name: uncomment OpenSAML encoding debugging
  lineinfile: line="log4j.category.OpenSAML.MessageEncoder=DEBUG" regexp="^\s*#?\s*log4j.category.OpenSAML.MessageEncoder=DEBUG" state=present dest=/etc/shibboleth/shibd.logger
  sudo: yes

- name: Restart apache
  service: name=apache2 state=restarted
  sudo: yes

- name: Restart shibd
  service: name=shibd state=restarted
  sudo: yes
