---
- name: checkout devstack
  git:
    repo: "{{ devstack_repo }}"
    dest: /home/vagrant/devstack
    version: "{{ version }}"

- name: local.conf
  template:
    src: local.conf.j2
    dest: /home/vagrant/devstack/local.conf

- name: source openrc in profile
  lineinfile:
    dest: /home/vagrant/.profile
    regexp: ".*openrc"
    line: '. /home/vagrant/devstack/openrc'
    state: present

- name: run devstack
  shell: ./stack.sh >> /home/vagrant/stack.sh.log 2>&1
  args:
    chdir: /home/vagrant/devstack
    creates: /home/vagrant/devstack/stack-screenrc

- name: Update identity and service providers policy
  lineinfile:
    dest: /etc/keystone/policy.json
    regexp: '^(\s*)"identity:{{ item }}": "rule:admin_required",\s*$'
    line: '\1"identity:{{ item }}": "",'
    backrefs: yes
    state: present
  with_items:
    - "list_identity_providers"
    - "get_identity_providers"
    - "list_service_providers"
    - "get_service_provider"
  sudo: yes

- name: Setup Mercador router
  ini_file:
    dest: /etc/keystone/keystone-paste.ini
    section: 'filter:mercador_extension'
    option: 'paste.filter_factory'
    value: 'keystone.contrib.mercador.routers:MercadorRouter.factory'
  sudo: yes

- name: Setup Mercador Auth
  ini_file:
    dest: /etc/keystone/keystone-paste.ini
    section: 'filter:mercador_auth'
    option: 'use'
    value: 'egg:keystone#mercador_auth'
  sudo: yes
