---
- name: checkout devstack
  git:
    repo: "{{ devstack_repo }}"
    dest: /home/vagrant/devstack
    version: "{{ version }}"
    update: no

- name: local.conf
  template:
    src: local.conf.j2
    dest: /home/vagrant/devstack/local.conf

- name: source openrc in profile
  lineinfile:
    dest: /home/vagrant/.profile
    regexp: ".*openrc"
    line: '. /home/vagrant/devstack/openrc'
    state: present

- name: run devstack
  shell: ./stack.sh >> /home/vagrant/stack.sh.log 2>&1
  args:
    chdir: /home/vagrant/devstack
    creates: /home/vagrant/devstack/stack-screenrc
