---
- hosts: all-nodes
  roles:
    - common
  vars_files:
    - vars/common.yaml

- hosts: keystone-idp
  roles:
    - devstack

- hosts: keystone-sp
  roles:
    - devstack

- hosts: tester
  roles:
    - openstackclient

- hosts: devstack
  roles:
    - devstack
