#!/bin/sh

INVENTORY_FILE=.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
PRIVATE_KEY=~/.vagrant.d/insecure_private_key
ANSIBLE_USER=vagrant

ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_FORCE_COLOR=true ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --user=$ANSIBLE_USER --connection=ssh --private-key="$PRIVATE_KEY" --timeout=30 --inventory-file=$INVENTORY_FILE --extra-vars=@nodes.yaml -vvvv "$@"
