---
- name: Ensure dependencies are met
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - unzip
    - wget
    - psmisc
    - lsof # useful when debugging
    - openssh-server
    - iputils-ping
    - tcpdump
    - tar
    - python-dev
    - python-pip
    - python-virtualenv
    - libyaml-dev
    - libffi-dev
    - libssl-dev # for pyOpenSSL
    - gettext  # used for compiling message catalogs
    - pkg-config
    - curl
    - git
    - ntp
  register: depends_met
  sudo: yes

- name: Ensure stack dir exists
  file:
    dest: /opt/stack
    state: directory
    mode: 0777
    owner: vagrant
    group: vagrant
  sudo: yes

- name: Ensure virtualenv exists
  command: virtualenv /opt/stack/venv
  args:
    creates: /opt/stack/venv/bin/python

- name: Upgrade pip
  pip:
    name: pip
    virtualenv: /opt/stack/venv
    state: latest

- name: Update setuptools
  pip:
    name: setuptools
    virtualenv: /opt/stack/venv
    state: latest

- name: Checkout OpenStack client and depends from Git
  git:
    repo: https://git.openstack.org/openstack/{{ item }}
    dest: /opt/stack/{{ item }}
  with_items:
    - python-openstackclient
    - python-cinderclient
    - python-glanceclient
    - python-keystoneclient
    - python-neutronclient
    - python-novaclient

- name: Checkout sqlalchemy-migrate from Git
  git:
    repo: https://github.com/stackforge/sqlalchemy-migrate
    dest: /opt/stack/sqlalchemy-migrate

- name: Install sqlalchemy-migrate from git
  command: /opt/stack/venv/bin/python setup.py install
  args:
    chdir: /opt/stack/sqlalchemy-migrate

- name: Ensure requirements are installed
  pip:
    requirements: /opt/stack/{{ item }}/requirements.txt
    virtualenv: /opt/stack/venv
  with_items:
    - python-keystoneclient
    - python-cinderclient
    - python-glanceclient
    - python-neutronclient
    - python-novaclient
    - python-openstackclient

# ORDER IS IMPORTANT!! PBR breaks develop. Requirements must be first!!
- name: Git Develop for OpenStack components
  command: /opt/stack/venv/bin/python setup.py develop
  args:
    chdir: /opt/stack/{{ item }}
  with_items:
    - python-keystoneclient
    - python-cinderclient
    - python-glanceclient
    - python-neutronclient
    - python-novaclient
    - python-openstackclient
