---
- name: Ensure dependencies are met
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - unzip
    - wget
    - psmisc
    - lsof # useful when debugging
    - openssh-server
    - iputils-ping
    - tcpdump
    - tar
    - python-dev
    - python-pip
    - libyaml-dev
    - libffi-dev
    - libssl-dev # for pyOpenSSL
    - gettext  # used for compiling message catalogs
    - pkg-config
    - curl
    - git
    - ntp
  register: depends_met
  sudo: yes

- name: Ensure stack dir exists
  file: dest=/opt/stack state=directory mode=0777 owner=vagrant group=vagrant
  sudo: yes

- name: Install pip via easy_install
  command: easy_install -U pip
  sudo: yes

- name: Remove packaged pip
  apt: name=pip state=absent
  sudo: yes

- name: Update setuptools
  command: pip install -U setuptools
  sudo: yes

#- name: Get pip
#  shell: (cd /opt/stack && wget https://bootstrap.pypa.io/get-pip.py)
#  args:
#    creates: /opt/stack/get-pip.py
#
#- name: Ensure pip is installed
#  shell: (cd /opt/stack && python ./get-pip.py)
#  args:
#    creates: /usr/local/bin/pip
#  sudo: yes

- name: Checkout OpenStack client and depends from Git
  git: repo=https://git.openstack.org/openstack/{{ item }} dest=/opt/stack/{{ item }}
  with_items:
    - python-openstackclient
    - python-cinderclient
    - python-glanceclient
    - python-keystoneclient
    - python-neutronclient
    - python-novaclient

- name: Checkout sqlalchemy-migrate from Git
  git: repo=https://github.com/stackforge/sqlalchemy-migrate dest=/opt/stack/sqlalchemy-migrate

- name: Install sqlalchemy-migrate from git
  shell: (cd /opt/stack/sqlalchemy-migrate && python setup.py install)
  sudo: yes

- name: Git Develop for OpenStack components
  shell: (pip install -r requirements.txt && python setup.py develop)
  args:
    chdir: /opt/stack/{{ item }}
  with_items:
    - python-keystoneclient
    - python-cinderclient
    - python-glanceclient
    - python-neutronclient
    - python-novaclient
    - python-openstackclient
  sudo: yes
