---
- name: Ensure dependencies are met
  apt: pkg={{ item }} state=present
  with_items:
    - tar
    - unzip
    - psmisc
    - lsof # useful when debugging
    - git
    - ntp
    - openssh-server
    - wget
    - curl
    - iputils-ping
    - tcpdump
    - build-essential
    - gettext  # used for compiling message catalogs
    - pkg-config
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - libffi-dev
    - libssl-dev # for pyOpenSSL
    - python-dev
    - python-pip
    - python-virtualenv
  sudo: yes

- name: Ensure stack dir exists
  file:
    dest: /opt/stack
    state: directory
    mode: 0777
    owner: vagrant
    group: vagrant
  sudo: yes

- name: Ensure virtualenv exists
  command: virtualenv /opt/stack/venv
  args:
    creates: /opt/stack/venv/bin/python

- name: Ensure python modules are installed
  pip:
    name: {{ item }}
    virtualenv: /opt/stack/venv
    state: latest
  with_items:
    - pip
    - setuptools
    - lxml  # needed for saml2

- name: Checkout OpenStack client and depends from Git
  git:
    repo: https://git.openstack.org/openstack/{{ item }}
    dest: /opt/stack/{{ item }}
  with_items:
    - python-openstackclient
    - python-cinderclient
    - python-glanceclient
    - python-keystoneclient
    - python-neutronclient
    - python-novaclient

- name: Checkout sqlalchemy-migrate from Git
  git:
    repo: https://github.com/stackforge/sqlalchemy-migrate
    dest: /opt/stack/sqlalchemy-migrate

- name: Install sqlalchemy-migrate from git
  command: /opt/stack/venv/bin/python setup.py install
  args:
    chdir: /opt/stack/sqlalchemy-migrate

- name: Ensure requirements are installed
  pip:
    requirements: /opt/stack/{{ item }}/requirements.txt
    virtualenv: /opt/stack/venv
  with_items:
    - python-keystoneclient
    - python-cinderclient
    - python-glanceclient
    - python-neutronclient
    - python-novaclient
    - python-openstackclient

# ORDER IS IMPORTANT!! PBR breaks develop. Requirements must be first!!
- name: Git Develop for OpenStack components
  command: /opt/stack/venv/bin/python setup.py develop
  args:
    chdir: /opt/stack/{{ item }}
    creates: /opt/stack/venv/lib/python2.7/site-packages/{{ item }}.egg-link
  with_items:
    - python-keystoneclient
    - python-cinderclient
    - python-glanceclient
    - python-neutronclient
    - python-novaclient
    - python-openstackclient

- name: make /etc/opnstack
  file:
    path: /etc/openstack
    owner: root
    group: root
    mode: 0755
    state: directory
  sudo: yes

- name: Create clouds.yaml
  template:
    src: clouds.yaml.j2
    dest: /etc/openstack/clouds.yaml
  sudo: yes
