- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes

- name: start ntp service
  service: name=ntp state=started
  sudo: yes

- name: stop ntp service
  service: name=ntp state=stopped
  sudo: yes

- name: update date with ntp
  command: ntpdate {{ preferred_ntp_server }}
  sudo: yes
